// <auto-generated />
using System;
using Forum_App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forum_App.Data.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    [Migration("20230531155147_CreateAndSeedDb")]
    partial class CreateAndSeedDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Forum_App.Data.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6189515-c52f-4366-8182-6e7b4965149c"),
                            Content = "This is my first ever post",
                            Title = "My first post"
                        },
                        new
                        {
                            Id = new Guid("22faeae6-6db1-4a8d-8f4a-9ec3389489fc"),
                            Content = "This is just another post",
                            Title = "My second post"
                        },
                        new
                        {
                            Id = new Guid("3eaa2854-9ce8-4c77-ba90-f2d1a672a9c9"),
                            Content = "This is yet another post",
                            Title = "My third post"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
